config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :name, presence: true
  validates :comment, length: { minimum: 10 }, if: -> { comment.present? }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :description, length: { minimum: 160 }, if: -> { description.present? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    @comment.user = current_user
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.user == current_user
      @comment.destroy
      redirect_to post_path(@post)
    else
      render json: { errors: { comment: ['You are not owner of this comments'] } }, status: :forbidden
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user == current_user
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render json: { errors: { comment: ['You are not owner of this comments'] } }, status: :forbidden
    end
  end

  private

  # attr_reader :current_user

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
 
<div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
        <div class="card mb-3" style="max-width: 1000px;">
          <div class="row no-gutters">
            <div class="col-md-4">
                <p>
                  <strong><%= comment.name %>:</strong>
                  <p class="card-text"><%= comment.comment %></p>
               </p>
               <% if comment.user == current_user%>
               <p>   
                  <%= link_to 'Delete',[comment.post, comment], method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %>
               </p>
               <%end%>
            </div>
         </div>
      </div>
      </div>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
 <%= simple_form_for([@post, @post.comments.build], remote: true) do |f| %>

<div class="field">
  <div class="control">
    <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
  </div>
</div>
<%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title>BlogDemoRails5</title>
    <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/"></a>
  <form class="form-inline">
        
        <p class="navbar-text float-right">
    <% if user_signed_in? %>
      <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-outline-primary'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'btn btn-outline-success'  %>
    <% end %>
  </form>
</p>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  </ul>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
</form>
</nav>
    <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<div class="card" style="max-width: 540px;">
  <div class="card-header">

<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <ul class="list-group list-group-flush">
    <li class="list-group-item">
     <%= form.label :title %>
     <%= form.text_field :title %>
    </li>
    <li class="list-group-item">
      <div class="field">
       <%= form.label :image %>
       <%= form.file_field :image %>
      </div>
    </li>
     <li class="list-group-item">
      <div class="field">
       <%= form.label :description %>
       <%= form.text_area :description %>
     </div>
    </li>
    <li class="list-group-item">
    <div class="actions">
     <%= form.submit  %>
   </div>
    </li>
  </ul>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% content_for :page_title,  "Index" %>
    <% if user_signed_in? %>

<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			
		      <div class="media-content">
			   <div class="card mb-3" style="max-width: auto;">
            <div class="row no-gutters">
             <div class="col-md-4">
		        <p class="title is-4"><%= link_to post.title, post, class:"btn btn-primary"  %></p>
		      </div>
		    </div>
				
		    <div class="comment-count">
		    	<span class="tag is-rounded"><%= post.comments.count %> comments</span>
		    </div>
        
           <% if post.user == current_user%>
          <div>
          <%= link_to 'Edit', edit_post_path(post), class:"btn btn-primary" %> 
        </div>
        <br>
         <div>
               <p>   
                  <%= link_to 'Delete', post, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %>
               </p>
          <% end %>
		<% end %>
		</div>
	 </div>
	</div>
	</div>
</div>

<br>

<%= link_to 'New Post', new_post_path %>

<%end%>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"btn btn-success"%>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="row content">
    
    <div class="col-sm-9">
      <h4><small><%= link_to 'Create a New Post', new_post_path %></small></h4> 
      <h4><small><%= link_to 'See All Post', posts_path %></small></h4>
      
      <hr>
      <br><br>
      <div class="card mb-3" style="max-width: auto;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%=@post.title%></h5>
        <p class="card-text"><%= @post.description %>.</p>
        <p class="card-text"><small class="text-muted">Last updated <%= distance_of_time_in_words(Time.now, @post.updated_at) %> ago </small></p>
      </div>
    </div>
  </div>
</div>
  <div class="card mb-3" style="max-width: auto;">
  <div class="row no-gutters">
    <div class="col-md-4">
     <section class="section comments">
        <div class="container">
            <div class="comment-form">
                <hr />
                <h3 class="subtitle is-3">Leave a reply</h3>
                <%= render 'comments/form' %>
            </div>
        </div>
      </section>
       
     </div>
    </div>
  </div> 
      <h3><span class="badge"><%= @post.comments.count %></span>Comments</h3><br>
      
      <div class="row">
        <div class="col-sm-2 text-center">
        </div>
        <div class="col-sm-10">
            <p><%= render @post.comments %></p>
          <br>
        </div>
       
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>